#!/usr/bin/env bash
# Redirecting to another page

sudo apt-get -y update;
sudo apt-get -y install nginx;
sudo service nginx start;
sudo chmod 777 /var/www/html/index.nginx-debian.html;
sudo chmod 777 /etc/nginx/sites-available/;
sudo chmod 777 /etc/nginx/sites-available/default;
sed -i "/listen 80 default_server;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default;
echo "Hello World" > /var/www/html/index.nginx-debian.html;
sudo nginx -s reload;
