#!/usr/bin/env bash
# Custom 404 page that contains the string Ceci n'est pas une page.

sudo apt-get -y update;
sudo apt-get -y upgrade;
sudo apt-get -y install nginx;
sudo service nginx start;
sudo chmod 777 /var/www/html/index.nginx-debian.html;
sudo chmod 777 /etc/nginx/sites-available/;
sudo chmod 777 /etc/nginx/sites-available/default;
sed -i "/listen 80 default_server;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart;

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sed -i "/listen 80 default_server;/ a error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
