#!/usr/bin/env bash
# displays Holberton School 10 times
i=0
f=101
while [ $i -lt $f ]
do
    if [ $((i%15)) = 0 ]
    then
	echo "FizzBuzz"
    elif [ $((i%3)) = 0 ]
    then
	echo "Fizz"
    elif [ $((i%5)) = 0 ]
    then
	echo "Buzz"
    else
	echo "$i"
    fi
    (( i+=1))
    done