#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and Hi
i=0
while [ $i -lt 11 ]
do
    if [ $i = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    (( i+=1 ))
done
