#!/usr/bin/env bash
#bad luck
i=1
f=21
while [ $i -lt $f ]
do
case $i in
    4)
	echo $i
	echo "bad luck from China"
	;;
    9)
	echo $i
	echo "bad luck from Japan"
	;;
    17)
	echo $i
	echo "bad luck from Italy"
	;;
    *)
	echo $i
	;;
esac

(( i+=1 ))

done