#!/usr/bin/env bash
# File school exist or not
v="school"
if [ -e "$v" ]
then
    echo "school file exists"
    if [ ! -s "$v" ]
    then
	echo "school file is empty"
    else
	echo "school file is not empty"
    fi
    if [ -f "$v" ]
    then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi